# Generated by Django 4.0.1 on 2022-02-06 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donation_type', models.CharField(choices=[('0', 'reg'), ('5', '5'), ('10', '10'), ('20', '20')], default='Free', max_length=200)),
                ('price', models.IntegerField(default=15)),
                ('description', models.TextField()),
                ('stripe_plan_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('postcode', models.CharField(blank=True, max_length=500, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(max_length=80, null=True)),
                ('country', models.CharField(max_length=80, null=True)),
                ('Donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monthly_donation.donation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_Active_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('user_Donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_donation.donors')),
            ],
        ),
    ]
