# Generated by Django 4.0.1 on 2022-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description_one',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30')], default='Free', max_length=200),
        ),
    ]
